### ISSUE TITLE
Integrate 1Hive Best Practices

### ISSUE THREAD

**Issue by yeqbfgxjiq** [aragoncoop/coop-dao-docs#2]
https://github.com/1Hive/handbook

**Comment by lkngtn** [comment]
Ended up moving this here: http://1hive.org/handbook.html which is hosted in this repo: https://github.com/1Hive/website

Though I think you may have already incorporated most of it the coop docs already. :)

**Comment by yeqbfgxjiq** [comment]
@lkngtn Continuously impressed with your writing. Been reading through the og [Coop Workflow](https://hackmd.io/pUuLOvlQQoygsaNv0hQ8Jg?view) and [1Hive Handbook](http://1hive.org/handbook.html) and the more I read them the more I like them. Very very good writing. All the words matter and the concepts are clear. I'm still working on that on my end... lol

Anyways, closing this since I've created [a new issue on the fork](https://github.com/burrrata/the-coop/issues/10) to refine the framework for The Coop in a way that focuses on dev ux and incentives around building/doing stuff.
