### ISSUE TITLE
Hive Commons License

### ISSUE THREAD

**Issue by yeqbfgxjiq** [aragoncoop/coop-dao-docs#5]
The Docusaurus template had a copyright thing at the bottom. I changed it to "Released under the Hive Commons License 2019" to the bottom of the homepage. I have no idea if that's the best way to present the licence though. Any feedback would be warmly appreciated :)

**Comment by lkngtn** [comment]
I don't think we should use it just yet because there isn't a license document, and no documentation on how to actually be compliant. 

I'm also not sure how relevant it would be for content like this, perhaps we should use the CC0 1.0 Universal License if any license at all.

**Comment by yeqbfgxjiq** [comment]
Honestly I threw it in here to force myself to learn how it works lol ([Cunningham's Law](https://meta.wikimedia.org/wiki/Cunningham%27s_Law))

What license would you recommend though?

**Comment by yeqbfgxjiq** [comment]
[Forked and fixed](https://github.com/burrrata/the-coop). New license is GPLv3, but open to changing that if people feel strongly about it. Holding off on merging until the coop decides if they want to move forward with the project or not.
